### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by masane19971203** [masane19971203/chat-space#7]
# IPアドレス
18.176.69.90

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正必要箇所]
### ①「Log in」「Sign up」「Edit Accoun」の文字の色をオレンジから黒に修正しましょう。

[参考]
https://master.tech-camp.in/curriculums/4265

<img width="1310" alt="文字色" src="https://user-images.githubusercontent.com/65144927/83843542-2ba1f000-a740-11ea-87be-48e63cd48d2c.png">

### ②グループ概要とメッセージ履歴の間に色をつけて区切りをつけましょう。

[参考]
https://master.tech-camp.in/curriculums/3944

<img width="751" alt="ChatSpace_フロント実装" src="https://user-images.githubusercontent.com/65144927/83843610-52602680-a740-11ea-9606-527a23a1f48d.png">


### ③グループ概要のメンバーを[Member]にしましょう。

<img width="772" alt="Editボタン" src="https://user-images.githubusercontent.com/65144927/83843764-a9fe9200-a740-11ea-88b4-64ca85da69ad.png">


### ④メッセージ投稿フォームの仕様を今一度カリキュラムを見直し、入力フォーム及びSendボタンの幅を確認し調整しましょう。（type a messageの前に余分な10pxが含まれているように見えます。また、Sendボタンの幅が少し狭いように見えます）

<img width="691" alt="投稿フォーム見本" src="https://user-images.githubusercontent.com/65144927/83843974-17122780-a741-11ea-9605-9046f4250d10.png">





修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mutorisa** [comment]
早速修正後、再度ご提出ありがとうございます！お疲れ様でした‼︎
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
